dis-moi/extension

src/components/atoms/Button/AddNoticeButton/AddNoticeButton.tsx
https://trello.com/c/2rYCPamv/468-simplifier-les-labels-quand-pas-de-contribution-sur-la-page
Still need "+" icon
=> fix(AddNoticeButton): changes value

src/app/profiles/App/index.tsx, views/profiles.pug
(as on the wordpress dismoi website)
=> fix(profiles): Remove fonts style from the app and rely on google fonts

README.md, manifest/base.js
Following discussion here : https://groups.google.com/a/chromium.org/g/chromium-extensions/c/zs8CFXLORhs
=> fix: remove unneeded `activeTab` permission

src/app/options/App/Header/Header.tsx
pull request demandée dans le cadre d'une formation
=> feat: update informer link

src/app/profiles/App/Profiles/Profile/FeaturedNotice.tsx
aligns the behaviour with the home of dismoi.io
=> fix(FeaturedNotice): aligns image on the left for mobiles

src/app/profiles/App/Profiles/Profile/ProfileNoticeListItem.tsx, src/components/atoms/icons/Pin.tsx, src/components/atoms/icons/index.ts
changes position of the pinned websites.
=> fix(profiles): changes on profiles details

src/webext/createMessageHandler.ts
https://trello.com/c/I8tHGr5P/586-bulle-qui-persiste-sur-youtube-apres-avoir-mis-du-temps-%C3%A0-apparaitre
=> fix(firefox): When navigating to another page wrong tab URl was transmited

src/api/fetchCategories.ts, src/app/actions/categories.ts, src/app/actions/helpers.ts, src/app/lmem/category.ts, src/app/lmem/contributor.ts, src/app/profiles/App/Profiles/List/ProfileList.stories.tsx, src/app/profiles/App/Profiles/List/ProfileList.tsx, src/app/profiles/App/Profiles/List/withConnect.ts, src/app/profiles/App/useContributorsFilters.ts, src/app/profiles/store/reducers/categories.reducer.ts, src/app/profiles/store/reducers/index.ts, src/app/profiles/store/sagas/categories.saga.ts, src/app/profiles/store/sagas/index.ts, src/app/profiles/store/selectors/categories.ts, src/app/profiles/store/selectors/contributors.ts, src/app/profiles/store/selectors/notices.ts, src/app/profiles/store/selectors/subscriptions.ts, src/app/store/collection/reducers/index.ts, src/app/store/collection/selectors.ts, src/components/molecules/Filters/Filters.stories.tsx, src/components/molecules/Filters/FiltersCheckboxes.tsx, test/fakers/generateContributor.ts
> Rely on backend PR [#272](https://github.com/dis-moi/backend/pull/272)
=> feat(contributor): Allow contributors to be filtered by categories

src/app/background/index.ts, src/app/background/sagas/serviceMessage.saga.ts, src/app/content/App/Notice/NoNotice/NoNoticeScreen.tsx, src/app/content/App/Question/ConfirmationScreen/ConfirmationScreen.tsx, src/app/content/App/Question/FormScreen/QuestionForm/QuestionForm.tsx, src/app/content/App/ServiceMessage/ServiceMessage.stories.tsx, src/app/content/App/Subscriptions/Subscriptions.tsx, src/app/profiles/App/Profiles/List/ProfileList.tsx, src/app/profiles/App/Profiles/Profile/SimilarProfiles.tsx, src/app/profiles/App/index.tsx, src/app/profiles/App/pathToContributor.ts, src/app/profiles/store/sagas/locationChange.saga.ts, src/components/molecules/Popin/PopinBottomBar.tsx, src/webext/openOptionsTab.ts
Need wording review @MaartenLMEM .
@graemehoffman instead of :
- https://www.dismoi.io/informateurs/ 
- https://www.dismoi.io/informateurs/16/Le-Meme-en-Mieux
new URLs are now :
- https://www.dismoi.io/sources/ 
- https://www.dismoi.io/sources/16/Le-Meme-en-Mieux
=> chore(wording): Change "informateur" to "source".

.env.proding, .env.production, .env.staging, docs/UNINSTALL.md, src/app/background/index.ts, src/app/background/sagas/install.ts
Redirection page on the website has been updated to redirect with the parameters.
Uninstall form now include an hidden field for the  `extensionId`.
=> feat(uninstall): Add `extensionId` parameter to uninstall URL

src/components/organisms/NoticeDetails/DetailsContent.ts, src/components/organisms/NoticeDetails/Message.tsx
=> fix(DetailsContent): changes margins to improve readibility

.eslintrc.json, docs/MATCHERS.md, src/app/background/sagas/tab.ts, src/app/background/selectors/index.ts, src/app/content/api.ts, src/app/lmem/matchingContext.ts, src/app/utils/doesDocumentMatchExpression.ts, src/webext/contentScript.ts, src/webext/createActionsListener.ts, src/webext/createMessageHandler.ts, test/app/lmem/findMatchingOffersAccordingToPreferences.ts
> https://github.com/dis-moi/backend/pull/295
=> feat(matcher): Allow to match a page based on its content

src/api/fetchNotice.ts, src/app/lmem/contributor.ts, src/app/lmem/notice.ts, src/app/profiles/App/Pages/Profiles/Profile/FeaturedNotices.tsx, src/app/profiles/App/Pages/Profiles/Profile/Profile.stories.tsx, src/app/profiles/App/Pages/Profiles/Profile/Profile.tsx, src/app/profiles/App/Pages/Profiles/Profile/ProfileNoticeList.tsx, src/app/profiles/App/Pages/Profiles/Profile/ProfileNoticeListItem.stories.tsx, src/app/profiles/App/Pages/Profiles/Profile/ProfileNoticeListItem.tsx, src/app/profiles/store/sagas/contributor.saga.ts, src/app/profiles/store/selectors/index.ts, test/fakers/generateContributor.ts, test/fakers/generateNotice.ts
> Depends on https://github.com/dis-moi/backend/pull/296
Fix  https://trello.com/c/IOThAQOA/565-jusqu%C3%A0-5-contributions-phares-%C3%A0-un-m%C3%AAme-profil
=> fix(featured): Introduce partial notice data model

.github/ISSUE_TEMPLATE/bug_report.md
When a user open an issue we ask him to fill in these blanks:
Close #640
=> Create an issue template

src/app/profiles/App/Pages/Profiles/Profile/ProfileIntro.tsx
=> fix(Avatar): forces to reset WP max-width

package.json
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license
> https://spdx.org/licenses/
=> chore: Fix licence format in package.json

src/components/molecules/Popin/PopinBottomBar.tsx
=> fix(i18n): translator: missingKey fr-FR #833

src/components/organisms/NoticeDetails/NoticeDetails.tsx, src/i18n/resources/en/extension.json, src/i18n/resources/fr/extension.json
=> fix(i18n): button cancel and apos #840

CHANGELOG.md, package.json, src/app/background/sagas/serviceMessage.saga.ts, src/app/content/App/ServiceMessage/ServiceMessage.stories.tsx, src/app/profiles/App/Pages/index.tsx, src/app/profiles/App/ProfileTabs.tsx, src/app/profiles/App/SimilarProfiles/SimilarProfiles.tsx, src/app/profiles/App/pathToContributor.ts, src/app/profiles/routes/index.ts, src/app/profiles/store/sagas/locationChange.saga.ts, src/components/molecules/Popin/PopinBottomBar.tsx, src/i18n/resources/en/extension.json, src/i18n/resources/en/profiles.json, src/i18n/resources/fr/extension.json, src/i18n/resources/fr/profiles.json, src/webext/openOptionsTab.ts
=> refactor(extension): change labels for éclaireur

src/i18n/resources/en/extension.json
=> English translation - extension

src/i18n/resources/en/profiles.json
All set - the only thing I'm not sure about is the changed date format.
=> English translation - profiles

src/app/profiles/App/Pages/index.tsx
point 1 de #852 
Redirect all profiles trafic from /en to /eclaireurs
=> feat: redirect path from /en/* to /eclaireurs  #852

src/app/profiles/App/Pages/Profiles/Profile/ProfileIntro.tsx
=> fix(Avatar): adds height value

package.json
=> chore(storybook): change storybook script package.json #865

src/app/utils/getMessageWithMediaPlayer.spec.ts, src/app/utils/getMessageWithMediaPlayer.ts, src/components/organisms/NoticePreview.stories.tsx, test/fakers/generateNotice.ts
=> fix(Notices): youtube regex with link

src/app/profiles/App/Pages/Profiles/ContextPopin.tsx, src/app/profiles/App/Pages/Profiles/List/ProfileList.tsx, src/app/profiles/App/Pages/Profiles/List/withConnect.ts, src/app/utils/onContributorExampleClick.ts, src/components/molecules/Popin/PopinParagraph.tsx, src/i18n/resources/en/profiles.json, src/i18n/resources/fr/profiles.json, yarn.lock
closes #890
@MaartenLMEM I did the translations myself, I think we need a second proofreading
=> feat(linkContributor): Change of link on contributor boxes #890

docs/CONTRIBUTING.md, docs/I18N.md, src/i18n/README.md
=> docs(i18n): add new readme

src/app/background/sagas/refreshMatchingContexts.ts
=> perf: debounce matching-contexts refresh triggers

src/app/content/index.ts, src/app/content/sagas/notices.ts, src/app/content/sagas/ui/index.tsx, src/app/content/sagas/watchUnload.saga.ts, src/app/content/sagas/watchUrls.saga.ts
=> chore(logger): Use trace log level instead of info

docs/EXCLUDED_MATCHINGS.md, docs/EXCLUSION.md, src/app/background/sagas/watchActivatedTab.saga.ts
While exploring the browser action title feature, I had to go through all the *exclusion* mechanism again and I produce a bit of doc in the process.
@MaartenLMEM please read this carefully.
This is also interesting, from the extension perspective, for the [workflow issue in the backend](https://github.com/dis-moi/backend/pull/287). 
> By the way I think we should have a similar schema in the extension repository.
=> Excluded patterns and restricted contexts

src/app/utils/getMessageWithMediaPlayer.spec.ts, src/app/utils/getMessageWithMediaPlayer.ts
=> fix(messageWithYoutubePlayer): display video after text

src/app/profiles/App/Pages/Profiles/ContextPopin.tsx, src/app/utils/onContributorExampleClick.ts, src/i18n/resources/en/profiles.json, src/i18n/resources/fr/profiles.json
=> feat(seeExampleButton): two step popin

src/app/utils/onContributorExampleClick.ts
closes #933 
closes #890
more details: https://github.com/dis-moi/extension/issues/933#issuecomment-831752563
=> fix(contextPopin): close after click

docs/CONTRIBUTING.md, docs/TESTING.md
Added a few lines on how to test new releases in Firefox Staging & Proding, following our conversation @lutangar
=> Update CONTRIBUTING.md - Firefox Staging testing

src/app/background/index.ts, src/app/background/sagas/serviceMessage.saga.ts, src/app/background/sagas/tab.ts, src/i18n/resources/en/extension.json, src/i18n/resources/fr/extension.json
=> feat(backgroundTranslation): serviceMessage

package.json, src/i18n/date.ts, src/i18n/format.spec.ts, src/i18n/format.ts, src/i18n/index.ts, src/i18n/resources/en/extension.json, src/i18n/resources/fr/extension.json, yarn.lock
Update date-fns and import required locales. Add some tests.
Fix #927
=> fix(i18n): Fix i18n date formatting

src/app/profiles/App/OnBoarding/index.tsx, src/app/utils/isRedirectedFromExtensionInstall.ts
=> fix(onBoardingRestart): memoize onboarding

src/app/content/index.ts, src/app/hocs/withTitle.tsx
on Content app, 18n have to be initialized before store to get the titles 
closes #950
=> fix(extension): initialize i18next before store

src/i18n/i18n.spec.ts, src/i18n/resources/en/profiles.json, src/i18n/resources/fr/profiles.json
=> fix(i18n): date format on translate file

src/app/profiles/App/Pages/Profiles/Profile/ProfileNoticeListItem.tsx
=> fix(profileNoticeListItem): fix storybook issue closes #988

.storybook/webpack.config.js, src/app/profiles/App/OnBoarding/Steps/Step2.tsx, src/app/profiles/App/Pages/Profiles/List/ProfileList.tsx, src/index.d.ts, webpack.profiles.config.js
@JalilArfaoui i pushed with --no-verify
could you check and tell me if it's ok please thx
closes #1006
=> chore(profilesonboarding): configure webpack for video assets

src/app/profiles/App/Pages/Profiles/Profile/ProfileNoticeListItem.tsx
=> fix(profile): display link

src/components/organisms/NoticeDetails/NoticeDetails.tsx
=> fix(youtubeVideoMessage): use notice state to memoize formated message

src/app/profiles/App/Pages/Profiles/Profile/Profile.tsx
> see https://github.com/dis-moi/extension/pull/993#issuecomment-851507753 and #922 for background
=> feat(profiles): Remove old install block when not connected

src/components/molecules/SidebarBox/ExplainingVideoMessageBox.tsx
=> fix(profiles): Fix add to browser install trigger

src/app/profiles/App/OnBoarding/OnBoarding.tsx, src/app/profiles/App/OnBoarding/Steps/index.ts, src/app/profiles/App/OnBoarding/components/Modal.tsx, src/app/profiles/App/OnBoarding/index.tsx, src/app/profiles/App/Pages/Profiles/List/ProfileList.tsx, views/profiles.pug, webpack.profiles.config.js
chunk name changed for OnBoarding.chunk.js, we mustn't to update path in `functions.php wp_register_script` when we push in prod
=> fix(chunk): onboarding chunk path

src/app/profiles/App/ContextPopin/ContextPopin.tsx
=> fix(popin): del className bulle-installer

src/app/content/store/selectors/index.ts, src/app/profiles/store/selectors/contributors.ts, src/app/profiles/store/selectors/notices.ts, src/libs/domain/contributor.ts, src/libs/domain/notice.ts, src/libs/i18n/index.ts, src/libs/utils/sortByLocale.ts, test/fakers/generateContributor.ts, test/fakers/generateNotice.ts
=> feat(i18n): sort by language contributors and notices

src/app/background/store/sagas/subscriptions.saga.ts, src/app/background/store/sagas/tracking/posthog/trackContributor.saga.ts, src/libs/store/actions/subscription.ts
=> feat(tracking): Add a flag to identify an automatic subscription

.storybook/preview.tsx
=> fix(storybook): import

src/app/background/store/sagas/tracking/posthog/trackContributor.saga.ts, src/app/background/store/sagas/tracking/posthog/trackNotice.saga.ts, src/app/background/store/selectors/subscriptions.selectors.ts, src/app/content/store/selectors/index.ts, src/libs/domain/contributor.ts, src/libs/domain/notice.ts
Including the relayer info if presents.
Close #1056
=> feat(tracking): Add notice and contributor fields to tracked properties

docs/tracking/POSTHOG.md, src/app/background/store/sagas/tracking/posthog/index.ts, src/app/background/store/sagas/tracking/posthog/trackUser.saga.ts, src/libs/tracking/posthog.ts, src/libs/tracking/utils.ts
Retrieve info as PostHog would do on the browser side and update doc.
> Note: utils.ts in tracking libs, is taken from PostHog, I therefore declined all responsability about its content :p
=> feat(tracking): Add browser, platform and devices info

src/libs/i18n/date.ts, src/libs/i18n/format.ts
#980 after a first quick win, new PR to avoid crash related to this commit #1f2be30ce86cb2b2cc6f129057708ded2285a4fb
=> refactor(i18n): avoid crash date

src/app/profiles/App/Pages/Profiles/Profile/ProfileIntro.tsx, src/app/profiles/App/Pages/Profiles/Profile/ProfileNoticeListItem.tsx
As discussed, few design tests to improve Users's understanding
=> chore(Profiles/Notice)

src/app/profiles/App/OnBoarding/LazyOnBoarding.tsx, src/app/profiles/App/OnBoarding/OnBoarding.tsx, src/app/profiles/App/OnBoarding/index.tsx, src/app/profiles/App/OnBoarding/withConnect.ts
closes #1047
@MaartenLMEM dans le backoffice il suffira de paramétrer `pk_campaign=installed-contributors-list` pour afficher la welcome bulle
=> feat(onboarding): trigger welcome bulle

src/app/profiles/App/Pages/Profiles/Profile/ProfileBanner.tsx, src/app/profiles/App/Pages/Profiles/Profile/ProfileIntro.tsx, src/components/organisms/Contributor/ContributorLarge.tsx
=> fix(profile): single profile bannière

src/libs/domain/contributor.ts, src/libs/utils/sortByLocale.ts
=> fix: list contributors ordering

.env.development.example, .env.proding, .env.production, .env.staging, docs/EXCLUDED_MATCHINGS.md, manifest/proding/chromium.js, manifest/production/chromium.js, manifest/staging/chromium.js, src/app/content/App/Question/PreviewScreen/PreviewScreen.stories.tsx
> see https://github.com/dis-moi/backend/issues/417
> and related PR https://github.com/dis-moi/backend/pull/426
=> chore: rename occurrences of bulles.fr to equivalent dismoi.io domain

src/app/profiles/App/OnBoarding/components/Landing.tsx, src/app/profiles/App/OnBoarding/components/Line.tsx, src/app/profiles/App/OnBoarding/components/Modal.tsx, src/app/theme.ts
=> fix(onboarding): responsive on height

.storybook/preview.tsx, src/app/background/index.ts, src/app/content/App/Contribute/ContributeScreen/SubmitContributionForm/Step1.tsx, src/app/content/App/Contribute/ContributeScreen/SubmitContributionForm/Step2.tsx, src/app/content/App/Contribute/ContributeScreen/SubmitContributionForm/SubmitContributionForm.tsx, src/app/content/App/Contribute/ContributeScreen/SubmitContributionForm/withReduxForm.ts, src/app/content/App/Notice/NoNotice/NoNoticeScreen.stories.tsx, src/app/content/App/Notice/NoNotice/NoNoticeScreen.tsx, src/app/content/hocs/withTitle.tsx, src/app/profiles/store/sagas/index.ts, src/components/atoms/Forms/Error/Error.ts, src/components/atoms/Forms/Input/Input.ts, src/components/atoms/Forms/Textarea/Textarea.ts, src/libs/i18n/resources/en/extension.json, src/libs/i18n/resources/fr/extension.json, yarn.lock
closes #1126
For you @newick 
@lutangar I have a typescript issue, i have to push --no-verify, could check ?
=> feat(contribution): new no notice screen

src/components/atoms/Contributor/ContributorInfos.ts, src/components/organisms/Contributor/ContributorsList.ts
=> fix(profilesList): changes list item width

yarn.lock
This reverts commit ffd9e62c8ef343b0a5b5e3187abb4f931ec597b9.
=> fix: revert "fix: yarn lock"

manifest/base.js, manifest/development/chromium.js, manifest/development/firefox.js, manifest/index.js, manifest/proding/chromium.js, manifest/proding/firefox.js, manifest/production/chromium.js, manifest/production/firefox.js, manifest/staging/chromium.js, manifest/staging/firefox.js, src/components/molecules/Popin/PopinBottomBar.tsx, src/libs/facets/dismoi.facet.ts, src/libs/facets/lmel.facet.ts, src/libs/facets/useFacetName.hook.ts, webpack/config.plugins.js
=> feat: Adapt manifest.json to LMEL facet

src/components/organisms/NoticeDetails/NoticeDetails.tsx, src/libs/domain/notice.ts, src/libs/i18n/format.ts, test/fakers/generateNotice.ts
=> fix: date format on extension closes #1105

src/libs/i18n/resources/en/extension.json, src/libs/i18n/resources/fr/extension.json
=> fix(onboarding): fix onboarding url

src/components/website/atoms/CTAButton/CTAButton.tsx, src/components/website/molecules/Header/Header.tsx
=> feat(website): add install links instead of placeholders

package.json, src/app/profiles/App/Pages/index.tsx, src/app/profiles/App/pathToContributor.ts, src/index.d.ts, src/libs/facets/getPathPrefix.ts, yarn.lock
=> fix(profiles): getPathToContributor does not include path prefix

.env.lmel
=> fix(lmel): wrong store for LMEL

manifest/base.js, manifest/development/chromium.js, manifest/development/firefox.js, manifest/proding/chromium.js, manifest/proding/firefox.js, manifest/staging/chromium.js, manifest/staging/firefox.js, src/app/background/index.ts, src/app/background/store/sagas/handleBrowserAction.saga.ts, src/app/background/store/sagas/tracking/index.ts, src/app/background/store/sagas/tracking/posthog/index.ts, src/libs/store/actions/browser.ts
As per https://developer.chrome.com/docs/extensions/develop/migrate/api-calls#replace_browser_action_and_page_action_with_action
Relates to #1276
=> Manifest V3: Change browser action to action
