dis-moi/extension

- src/api/fetchMatchingContexts.ts
This was leading to call /api/v3/matching-contexts?contributors=undefined which return empty result
-> nothing was matching anymore -_-
> fix(matching-contexts): Fix a bug where matching contexts were empty

- src/app/actions/tabs.ts
- src/app/background/sagas/lib/sendToTab.saga.ts
- src/app/background/sagas/tab.ts
- src/app/lmem/tab.ts
- src/webext/createBrowserActionListener.ts
- test/app/actions.ts
Since we remove the `activeTab` permission we lost access to the tab URL in some part of the browser API.
We have a little hack to get the tab URL thus it may not be such an issue.
However it's not very future proof and from my point of view (maybe I missed something but) the `activeTab` tab permission seems relevant in our case.
Here, my implementation choice assumes a tab may not have an URL.
> fix: Browser action click not toggling UI

- .env.development.example
- .env.proding
- .env.production
- .env.staging
- src/app/background/sagas/refreshMatchingContexts.ts
**dev**
- Matching contexts: 5 minutes
- Contributors: 5 minutes
**staging & proding**
- Matching contexts: 5 minutes
- Contributors: 5 minutes
**production**
- Matching contexts: 30 minutes
- Contributors: 30 minutes
> I think for production it was the previously intended values.
Let me know if you think that some values would be more appropriate.
> chore: Change refresh intervals to values that make some sense

- src/app/profiles/App/Profiles/Profile/ProfileNoticeListItem.tsx
I was browsing https://www.dismoi.io/les-contributeurs/32/Colibri-ecolo and the screenshot of the second notice was not loading.
I wonder if it's a known issue @JalilArfaoui .
As for text itself, it's only supposed to appears on screen readers and if something prevent the image from loading.
> fix: Typo on sample notice screenshot alternative text

- src/api/postRating.ts
- src/app/actions/index.ts
- src/app/actions/notices.ts
- src/app/background/reducers/tabs.reducer.ts
- src/app/background/sagas/ratings/notices.saga.ts
- src/app/background/sagas/tracking/trackNotice.saga.ts
- src/app/content/sagas/notices.ts
- src/components/organisms/Notice/Notice.tsx
- src/components/organisms/NoticeDetails/NoticeDetails.tsx
- src/webext/getSelectedTab.ts
This PR aims to solve this :
@MaartenLMEM I got it wrong : This particular issue exists with or without `activeTab` permission (reproduced locally). 
This is a serious issue, despite its relation to notices ratings, because the failure breaks the whole background script, freezing the extension until browser reload.
The change here is to stop using the `tabs.query` (which usage I forgot to mention in my [forum post](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/zs8CFXLORhs)) and use instead the true tab that sent the event.
It also makes more sense functionally to use the action metadata to know where the event occured than trying to detect it afterward based on the current active tab, which may have changed between the actual event and the rating saga handling. …
> fix: use meta URL in ratings actions instead of tabs.query

- src/api/call.ts
- src/app/profiles/store/sagas/contributors.saga.ts
I’m trying this because I noticed that under some circumstances, the profiles app does not include the `Origin` when fetching the API. It may be because it’s only a GET (`/contributors`), but then it complains that it does not have a access-control-allow-origin …
> fix: set fetch to use CORS mode

- src/api/fetchNotice.ts
- src/app/actions/notices.ts
- src/app/background/reducers/resources/index.ts
- src/app/background/reducers/resources/notices.reducer.ts
- src/app/background/reducers/tabs.reducer.ts
- src/app/background/sagas/tab.ts
- src/app/background/selectors/prefs.ts
- src/app/content/App/Notice/Details/index.tsx
- src/app/content/App/Notice/List/index.tsx
- src/app/content/reducers/notices.ts
- src/app/lmem/notice.ts
- src/app/profiles/App/Profiles/Profile/Profile.tsx
- src/app/profiles/App/Profiles/Profile/ProfileNoticeList.tsx
- src/app/profiles/App/Profiles/Profile/ProfileNoticeListItem.tsx
- src/app/profiles/store/reducers/notices.reducer.ts
- src/app/profiles/store/selectors/index.ts
- src/app/profiles/store/selectors/notices.ts
- src/components/organisms/Notice/Notice.tsx
- src/components/organisms/NoticeDetails/NoticeDetails.tsx
- test/fakers/generateNotice.ts
This commits clarifies between NoticeWithContributor and NoticeWithContributorId
Ideally, API should be consistent and always send relations Ids … (or GraphQL :-) ?)
Key (and fixing) change is in `src/app/profiles/store/selectors/index.ts`
> fix: profiles crashes because featured notices does not have relayersIds

- src/components/organisms/Contributor/ContributorLarge.tsx
https://trello.com/c/bQCOfgcw/569-supprimer-la-mention-description-non-renseign%C3%A9e-dans-les-profils
> chore(contributor): Remove contributor description placeholder

- webpack.profiles.config.js
Default image rule and the profile one were someway conflicting, explicitly include profiles app directory does fix an issue with the image being corrupted.
> fix(banner): Fix default banner not showing up.

- webpack.profiles.config.js
Beware @lutangar  : In Webpack rules, *all* rules that matches apply …
We have to use a `oneOf` rule to let only the first matching rule apply
> chore: fix profiles Webpack rules

- package.json
- src/api/call.ts
- src/app/actions/options.ts
- src/app/background/sagas/install.ts
- src/app/background/sagas/options.saga.ts
- src/app/background/sagas/serviceMessage.saga.ts
- src/app/content/App/ServiceMessage/withConnect.ts
- src/app/content/actions/goToContributor.ts
- src/app/matomo.ts
- src/webext/openOptionsTab.ts
- yarn.lock
I removed duplicated code for building a query string (for the ramda part I'm open to suggestion.
But I could as well keep the library instead of the custom function since it was there anyway and migth handl edge cases?
Or there's also the native URL and params browser API...
> feat: Add campaign param when redirecting to profiles for the first time

- src/app/content/sagas/contribution.ts
- src/app/content/sagas/question.ts
- src/app/sagas/effects/callAndRetry.ts
- src/app/sagas/error.ts
Since we have a blind spot on production monitoring right now, I wanted to keep this PR simple, without questioning the whole error tracking/logging mechanism that we may have to reconsider in a second stage.
> fix(contribution): track sendInBlue errors in Sentry

- src/app/content/App/Notice/Details/Details.stories.tsx
- src/app/lmem/format/message.ts
- src/app/utils/getMessageWithMediaPlayer.ts
- src/app/utils/linkify.ts
- src/components/organisms/NoticeDetails/Feedbacks.ts
- src/components/organisms/NoticeDetails/Message.tsx
- src/components/organisms/NoticeDetails/NoticeDetails.stories.tsx
- src/components/organisms/NoticeDetails/NoticeDetails.tsx
- src/components/organisms/NoticePreview.stories.tsx
- src/components/organisms/NoticePreview.tsx
- test/fakers/generateNotice.ts
I added on the Notice component the possibility of recognizing youtube URLs and replacing them with the player of the corresponding video. For that I have:
- created a getMessageWithYoutubePlayer file which takes the initial children (string) from the "Message" component and transforms it via a Regex by adding the youtube iframe, or returns nothing if the regex does not match
- imported this function into the "Message" component
- added a defautlMessageWithYoutubeVideo in generateNotice
- everything is visible in the storybook: http://localhost:6007/?path=/story/extension-notice-details--with-youtube-video
> Display Youtube player in notice when youtube link found

- src/app/background/sagas/serviceMessage.saga.ts
- src/app/content/App/ServiceMessage/ServiceMessage.stories.tsx
- src/app/profiles/App/Pages/index.tsx
- src/app/profiles/App/ProfileTabs.tsx
- src/app/profiles/App/SimilarProfiles/SimilarProfiles.tsx
- src/app/profiles/App/pathToContributor.ts
- src/app/profiles/routes/index.ts
- src/app/profiles/store/sagas/locationChange.saga.ts
- src/webext/openOptionsTab.ts
closes #827 
I added a new folder /routes in root of app/profiles with new file which export const SOURCES =/eclaireurs wherever it is needed
> feat(profiles): change link: sources to eclaireurs

- src/app/content/App/Account/About/index.tsx
- src/app/content/App/Account/Filters/Filters.tsx
- src/app/content/App/Account/Menu/index.tsx
- src/app/content/App/Contribute/ContributeScreen/index.ts
- src/app/content/App/Contribute/PreviewScreen/withTitle.ts
- src/app/content/App/Help/index.tsx
- src/app/content/App/Notice/Details/index.tsx
- src/app/content/App/Question/FormScreen/index.ts
- src/app/content/App/Question/PreviewScreen/withTitle.ts
- src/app/content/App/Subscriptions/index.tsx
- src/app/hocs/withTitle.tsx
- src/components/atoms/Button/AddNoticeButton/AddNoticeButton.tsx
- src/i18n/resources/en/extension.json
- src/i18n/resources/fr/extension.json
@christpet can you correct my english translation ?
@lutangar i add t function on withTitle HOC. It translate all titles (profiles and extension) but use only extension namespace to refer words (i18n use "extension" NS as defaultNS). It's ok for you ?
closes #871
> fix(i18n): t function on withTitle hoc #871

- src/app/content/App/Notice/List/List.stories.tsx
- src/app/content/App/Notice/List/ListContainer.ts
- src/app/content/App/Notice/List/index.tsx
- src/components/atoms/AddNoticeContainer.ts
- src/components/atoms/Button/AddNoticeButton/AddNoticeButton.tsx
- src/components/organisms/Notice/Container.ts
- src/components/organisms/Notice/Content.ts
A way to fix #850
@MaartenLMEM / @christpet visually it would be something like 
@gregoirelacoste could you find a way to hide the message if there's less than 2 notices?
> fix(NoticesList): way to display more than 2 notices

- src/app/background/sagas/refreshMatchingContexts.ts
- src/app/sagas/effects/callAndRetry.ts
- src/app/store/sagas/refreshContributors.saga.ts
fix: extension completely hangs after 6|10 retries of fetching contributors|matching-contexts
fixes #861
> fix: extension completely hangs after 6|10 retries 

- src/app/background/sagas/refreshContributors.ts
This is in order to avoid parallel fetching attemps in case previous one still hasn’t succeeded. With this, we only request a new refresh once previous one has succeeded.
Same spirit as #917 but for contributors
Related to #861
> perf: change contributors periodical refresh logic

- package.json
This should help with #362 : 
Instead of just running tests on pre-push, we now check : 
- tests
- typings
- code and style lint 
- build of extension and storybook
> chore: verify(all) on pre-push hook

- src/app/background/sagas/refreshMatchingContexts.ts
This is in order to avoid parallel fetching attemps in case previous one still hasn’t succeeded. With this, we only request a new refresh once previous one has succeeded.
Relates to #861
> perf: change matching contexts periodical refresh logic

- src/app/lmem/badge.ts
On some events we call update badge with 0 notices number and this was ignored.
Fix #916
> fix(badge): Badge reset on context not triggered

- src/app/profiles/App/OnBoarding/Steps/Step1.tsx
- src/app/profiles/App/OnBoarding/Steps/Step2.tsx
- src/app/profiles/App/OnBoarding/Steps/Step3.tsx
- src/app/profiles/App/OnBoarding/components/Buttons.tsx
- src/app/profiles/App/OnBoarding/components/Line.tsx
- src/app/profiles/App/OnBoarding/components/Title.tsx
- src/app/profiles/App/OnBoarding/components/Top.tsx
- src/app/profiles/App/OnBoarding/index.tsx
- src/app/utils/isChrome.ts
- src/i18n/resources/en/profiles.json
- src/i18n/resources/fr/profiles.json
closes #902 
last changes:
- new wording: Instead of "l'installation a réussi", it could be "L'extension est à jour"
- separate experience for Firefox and Chrome Users. On Firefox, only 2 steps, not the pinning part.
@newick @MaartenLMEM @coffeeandpixel
> feat(onBoardingEvolution): detect isChrome for step2, change wording

- package.json
Passes `git push` time from 4-5 minutes to 1min15 by *not* verifying that the build succeeds, and leave this check for CI jobs
> chore: quicker git push hook

- webpack/config.plugins.js
The array of susbcriptions was always empty since the env variable was never actually injected.
> This fix  #1012 and was previsouly introduced by @lutangar in fb7d13fec21b84352db4ebc7860256755ee78479 :roll_eyes:
> fix(subscriptions): Fix auto subscriptions

- src/app/profiles/App/Pages/Profiles/Profile/Profile.tsx
related to #1027
The issues was connected === undefined don't match with connected === false in:
``` js
{connected === false && (
<ExplainingVideoMessageBox contributor={contributor} />
)}
```
I fixed with `!connected &&`
A question : in connected reducer initial state is connected = undefined, why undefined and not false ?
> fix(newBlocksFirefox): change test connected in Profile

- src/app/hooks/useChangeLanguage.ts
- src/i18n/config.ts
- src/i18n/date.ts
- src/i18n/format.ts
- src/i18n/index.ts
> Following discussions about #989 with @gregoirelacoste on __Slack__
In my opinion the formatting exception shouldn't be silenced at all since because it's supposed to happens at dev time and fixed at dev time. 
However I can understanding @gregoirelacoste feeling about this, "it might happens anyway", that's why I'm trying to propose a middleground here:
- show an error message in console for the dev
- use default format if and only if it's a range error (format error in date-fns) and rethrow if it's something else.
> Maybe smthing else to do with Sentry?
This might sound picky, but this is important to understand the different level of errors and how we define might deal with it; define our strategy.
This also add  a default language constant and use it in `getLocale` and fix the …
> Invalid date proposal

- src/libs/api/APIStatusCodeError.ts
- src/libs/api/call.ts
I tried not to impact the current behavior but just to change the 4xx error behavior.
> see #360 for history
> chore: Differentiate 4xx Http errors from an actual server error

- src/libs/domain/matchingContext.ts
- src/libs/utils/doesDocumentMatchExpression.ts
fixes #1127 
Problem was :
- We filter in all matching contexts the ones which match current URL
- We filter again the remaining list to check if an xpath expression applies
- One notice has a bad xpath -> it breaks the whole matching for all notices, even those without XPath !
This commit  considers an xpath as non matching if the evaluation fails, and prints a warning to the website console.
> fix: bad xpath expression breaks matching for everyone

- .env.proding.lmel
- .env.production.lmel
- .env.staging.lmel
- loadEnv.js
> chore: add Chrome Web Store extensions ids for LMEL

- src/libs/i18n/index.ts
SSR is done with fallbackLng. Fix is easy for lememe.fr (set it to 'fr') but we’ll need something better for dismoi.io so that we’re able to SSR in the right langage depending or requested URL …
> fix: lememe.fr loads in english first

- manifest/production/chromium.js
Allow "https://*.lememe.fr" in externally_connectable
> fix: profiles and extension communication under Chromium
